services:
  llama-build:
    profiles: [build]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_JOBS: "20"
    image: opencode-llama.cpp:latest

  llama-server:
    profiles: [model]
    runtime: nvidia
    restart: unless-stopped
    image: opencode-llama.cpp:latest
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    networks:
      enhasa_network:
    volumes:
      - opencode-llama.cpp_hf-cache:/root/.cache/huggingface
      - ./models.ini:/models.ini
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command:
      - "--models-preset"
      - "/models.ini"
      - "--port"
      - "${PORT:-8080}"
      - "--host"
      - "${HOST:-0.0.0.0}"

volumes:
  opencode-llama.cpp_hf-cache:
