services:
  llama-server:
    runtime: nvidia
    restart: unless-stopped
    image: opencode-llama.cpp:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     PR_NUMBER: "21343"
    #     BUILD_JOBS: "12"
    #     GH_TOKEN: ${GH_TOKEN:-}
    ports:
      - "${PORT:-8089}:${PORT:-8089}"
    volumes:
      - opencode-llama.cpp_hf-cache:/root/.cache/huggingface
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - "-hf"
      - "${MODEL:-ggml-org/gemma-4-E4B-it-GGUF:Q4_K_M}"
      - "--jinja"
      - "-c"
      - "${CTX:-32768}"
      - "--port"
      - "${PORT:-8089}"
      - "--host"
      - "${HOST:-0.0.0.0}"
      - "-ngl"
      - "${NGLAYERS:-50}"
      - "-ot"
      - "${CPUMOE:-exps=CPU}"
      - "-fa"
      - "${FLASHATTN:-off}"
      - "-b"
      - "${BATCH:-256}"
      - "-ub"
      - "${UBATCH:-256}"
      - "-t"
      - "${THREADS:-20}"
      - "-tb"
      - "${THREADS_BATCH:-20}"
      - "--parallel"
      - "${PARALLEL:-1}"
      - "--mlock"
      - "--fit"
      - "off"
      - "-ctk"
      - "${CACHE_TYPE_K:-q4_0}"
      - "-ctv"
      - "${CACHE_TYPE_V:-q4_0}"
      - "--no-mmap"

volumes:
  opencode-llama.cpp_hf-cache:
